INSERT INTO "PostCategory" ("id", "name", "description") VALUES
  ('books', 'Books', 'Fiction, non-fiction, and more.'),
  ('movies', 'Movies', 'Action, drama, comedy, and more.'),
  ('series', 'TV Series', 'Drama, comedy, and more.'),
  ('music', 'Music', 'Rock, pop, classical, and more.'),
  ('gaming', 'Gaming', 'PC, console, mobile, and more.'),
  ('pcelectronics', 'PC & Electronics', 'Computers, laptops, phones, and more.'),
  ('household', 'Household & DYI', 'DYI, furniture, appliances, and more.'),
  ('animals', 'Animals', 'Dogs, cats, fish, and more.'),
  ('nature', 'Nature', 'Biology, hiking, and more.'),
  ('beauty', 'Beauty & Personal Care', 'Makeup, skincare, and more.'),
  ('vehicles', 'Vehicles', 'Cars, motorcycles, and more.'),
  ('fooddrinks', 'Food & Drinks', 'Recipes, restaurants, and more.'),
  ('education', 'Education', 'School, college, and more.'),
  ('babys', 'Babies & Kids', 'Toys, clothes, and more.'),
  ('fashion', 'Fashion', 'Clothes, accessories, and more.'),
  ('sports', 'Sports', 'Basketball, soccer, and more.'),
  ('travel', 'Travel', 'Vacations, destinations, and more.'),
  ('programming', 'Programming', 'Software development, coding, and more.');